### ISSUE TITLE
Handling of middle names

### ISSUE THREAD

**Issue by crsh** [marton-balazs-kovacs/tenzing#18]
Hi Marton,

a brief summary of our discussion thus far. The infosheet includes a field for author middle names. It should handle both full names and initials, which is currently not the case. I just had a quick look at the current behavior for

1. Full middle name
2. Initial with dot
3. Initial without dot
4. Multiple initials with dot

There are currently no errors. I saw the following behavior:

- In the author contribution list everything is printed as is.
- In the author affiliation list everything is correctly abbreviated to an initial with dot. However, if there are multiple initials, only the first one is kept.
- XML and JATS include everything as is.

I assume we want consistent behavior for all outputs (e.g., abbreviations)?

The line that currently does the abbreviation in the author affiliation list is this one: https://github.com/marton-balazs-kovacs/tenzing/blob/296f99b86a0d87c5ba0ca5791b2f17299b7c459e/R/print_contrib_affil.R#L33

Something like this should work and be reasonably robust:

~~~r
abbreviate <- function(x) {
    if(x != "") {
        gsub(x,  pattern = "^(.).*", replace = "\\1.")
    } else {
        NULL
    }
}

abbreviate_middle_names <- function(x) {
    split_names <- unlist(strsplit(x, split = " |\\."))
    initials <- unlist(lapply(split_names, abbreviate))
    paste(initials, collapse = " ")
}

name <- " p k j.p."
abbreviate_middle_names(name)          
~~~

~~~
[1] "p. k. j. p."
~~~

This works regardless even when some names are abbreviate with or without a colon and if a colon-abbreviated entry is missing a space.

If this looks good to you I could implement this for all outputs in a new PR.

**Comment by marton-balazs-kovacs** [comment]
This looks really good! Awesome solution. Thank you. Could you add it to the modules?

**Comment by jcolomb** [comment]
NB: middle names tend to be abandoned, as there is no place for it in orcid. see https://support.orcid.org/hc/en-us/articles/360006973853-Add-and-edit-your-name-on-your-ORCID-record

datacite (I think also crossref) have only surname and given-name (given name may include the initial of the middle name).
