### ISSUE TITLE
merge with contributor role creator ?

### ISSUE THREAD

**Issue by jcolomb** [marton-balazs-kovacs/tenzing#22]
see  https://colomb.shinyapps.io/contributorlist_creator/

and the corresponding  https://github.com/open-science-promoters/contibutor_manager/

got to work with latest credit and CRO ontologies (download the OBO files)
import author information from ORCID (name, institution, funding information)

I will definitively look at your outputs and copy it, but would love to actually merge the two application (at least their background).

**Comment by marton-balazs-kovacs** [comment]
Hi @jcolomb,

Thanks for writing! I've looked at your app and the corresponding github repo and indeed there are a lot of similarities even if the backend structure is a bit different (ie. we outsource the contributorship info collection while you do it in-app). It is great that you use the ORCID information and the CRO as well!

I will talk with the other collaborators about your project and proposition to merge and get back to you soon.

Again, great project!

Best,
Marton

**Comment by marton-balazs-kovacs** [comment]
Hi @jcolomb,

Could you send me an email please so we can set up a meeting?

Thanks,
Marton

**Comment by jcolomb** [comment]
julien.colomb@fu-berlin.de

**Comment by jcolomb** [comment]
for now, my app gets a tenzing output, we will keep it that way for now.
