### ISSUE TITLE
Feature request: ORCiD 

### ISSUE THREAD

**Issue by Trebicky** [marton-balazs-kovacs/tenzing#24]
This is a great tool!

Could you add a column for Orcid numbers for the authors' list generator?

Thanks.

**Comment by marton-balazs-kovacs** [comment]
Thank you for your interest!

Could you elaborate on that, please? How do you imagine the output? Just to be on the same page.

**Comment by crsh** [comment]
Some thoughts for the different outputs.

### Author contribution list

I don't immediately see a use-case for ORCID here.

### Affiliation list with affiliations

On the human-readable report we could include small ORCID icons for each author that link to the public profiles, no? We could use [academicons](https://jpswalsh.github.io/academicons/) for this.

### JATS-XML

The J4R standard [defines an ORCID field](https://jats.nlm.nih.gov/publishing/tag-library/1.2d1/attribute/contrib-id-type.html) for the JATS-XML, so we may include it like so:

~~~xml
<contrib>
<contrib-id authenticated="true" contrib-id-type="orcid">https://orcid.org/0000-0003-2354-0408</contrib-id>
<name>
<surname>Delon</surname>
<given-names>Wright</given-names>
</name>
<role content-type="https://dictionary.casrai.org/Contributor_Roles/Data_curation">Data curation</role>
<role content-type="https://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_review_%26_editing">Writing – review &amp; editing</role>
</contrib>
~~~

### `papaja`-YAML

ORCID would also be useful for the `papaja`-YAML. Support for structured inclusion of those is on [my todo-list](https://github.com/crsh/papaja/issues/342).

**Comment by jcolomb** [comment]
merge with #37 , also related to #22, #32
