### ISSUE TITLE
googlesheet integration

### ISSUE THREAD

**Issue by jcolomb** [marton-balazs-kovacs/tenzing#30]
It might be interesting to keep the spreadsheet on a google sheet, and read that spreadsheet with  the googlesheets4 package ?

people would have to enter the googlesheet url

**Comment by marton-balazs-kovacs** [comment]
Hi!

Thank you for the suggestion. In an earlier version of the app we used this solution. We wanted to avoid login, and therefore we only accepted public spreadsheets. Making a spreadsheet publicly available seemed difficult for users therefore we swapped to the current upload option.

However, the url option can be added again if users request it.

**Comment by jcolomb** [comment]
googlesheets4::gs4_deauth() can be used to use the API without login.
sheets can then be read from the share url.

https://googlesheets4.tidyverse.org/articles/articles/auth.html

**Comment by marton-balazs-kovacs** [comment]
Thank you for pointing this out. I think we used the googlesheets package. I will give it a try.

However, in the documentation they mention that: "read Sheets that are world-readable or readable by “anyone with a link" and "If you don’t need to access private Sheets, use gs4_deauth() to indicate there is no need for a token". From these comments, I assume that you do need to make the spreasheet public as it was the case before with our implementation.

**Comment by jcolomb** [comment]
I do not really know what public spreadsheet means here. 
I can give you access to https://docs.google.com/spreadsheets/d/1G9lkHmIPp2QwPXP3kxVWHkBoKwHaQ2gU80uYbItNDEE/edit?usp=sharing
but the file is still private ??

**Comment by marton-balazs-kovacs** [comment]
I gave the package a try. You are right. We used the googlesheets package previously and for that you needed to make the spreadsheet public on the web first and then share it. With googlesheets4 I did not need to do the first step. So I will add the URL read option to the app as an enhancement.

**Comment by jcolomb** [comment]
see #42

**Comment by jcolomb** [comment]
done in #55
