### ISSUE TITLE
Data pull: from orcid

### ISSUE THREAD

**Issue by jcolomb** [marton-balazs-kovacs/tenzing#37]
We could think of a way to populate the spreadsheet with  information collected on orcid.

We could use the default data input from the contributor list creator (return first name, surname, present affiliation, first funding entry).

At first, we could have simply a "add one or several author" function, so we do not have to deal with updating information that could have changed on orcid.

**Comment by jcolomb** [comment]
It should not be very difficult. one needs to think about the UX, though.

Another possibility, is to do everything in the other app and link them together having a: "output to tenzing" in my app?

I will work on the backend on my project first:
- dataframe output from yaml/Rlist
- get the present funding as a default.

**Comment by marton-balazs-kovacs** [comment]
I am not sure that I understand the "add one or several authors" part.

I thought we do not want to populate the spreadsheet with information from orcid "on google drive", but rather after the spreadsheet is read in the app, the app populates the columns that are missing information from orcid if possible. There is an option to check the uploaded spreadsheet in-app as well that can be used to check the populated spreadsheet before producing the output.

**Comment by jcolomb** [comment]
This workflow has 2 major flows:
- people with info on orcid will probably add the info in the sheet: there is no gain of time
- people trusting the system to use orcid will be pissed if there is a mistake there + the present funding and affiliation is not enough: most projects are published years after the funding and affiliation information has changed.

**Comment by marton-balazs-kovacs** [comment]
I am not sure that these are flows. If we make it clear that if you are fine with your information on orcid, you can leave out the columns that can be populated from orcid, and the spreadsheet is the primary input of information, people will act accordingly.

I think if some of them fill out the spreadsheet whereas their information could have been called from orcid, is not a big deal.

If some people have old information on orcid, they can easily write the new information in the spreadsheet, therefore the old info from orcid will be disregarded.

**Comment by jcolomb** [comment]
Will not be done in tenzing
