### ISSUE TITLE
YAML output error: Conceptualization listed for all authors even when no authors indicated for conceptualization

### ISSUE THREAD

**Issue by alexholcombe** [marton-balazs-kovacs/tenzing#45]
As you can see after uploading this infosheet - 
[infosheet_template (1).xlsx](https://github.com/marton-balazs-kovacs/tenzing/files/5185507/infosheet_template.1.xlsx)

in the YAML output, every author is listed for Conceputalization even though none were indicated.

**Comment by jcolomb** [comment]
I do not have the problem, did you use https://martonbalazskovacs.shinyapps.io/tenzing/ ?

**Comment by alexholcombe** [comment]
Thanks Julien, searching my browser history, I don't see any other URLs with "tenzing" in them, so it seems I must have used this link, but like you I'm not getting the error now! 
Do you know what other URL that I might have used? Need to delete any such URL from all our pages, but looking through the  webpages, I don't see any such URL.

**Comment by jcolomb** [comment]
I thought you might have started the app via the Rconsole, or use this : https://colomb.shinyapps.io/tenzing_devversion/ which is not documented outside of our slack.

**Comment by marton-balazs-kovacs** [comment]
As the currently deployed version is returning the correct values I am closing this issue.
