### ISSUE TITLE
Spreadsheet name

### ISSUE THREAD

**Issue by jcolomb** [marton-balazs-kovacs/tenzing#48]
"infosheet seems not to be a good name, write proposition in comments.

**Comment by jcolomb** [comment]
contributor table

**Comment by jcolomb** [comment]
tenzing table, tenzing sheet

**Comment by marton-balazs-kovacs** [comment]
contributor information sheet or table

**Comment by marton-balazs-kovacs** [comment]
changed infosheet to contributor_table everywhere in 7170c3f0b3a214783115ec03954aa8ca0fb9be55
