### ISSUE TITLE
Formatted XML preview

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [marton-balazs-kovacs/tenzing#5]
Hi Frederik,

I mentioned to you earlier that I could not find a good way to show the preview of the XML document output. Right now, we are showing the document as a text output ([see](https://github.com/marton-balazs-kovacs/tenzing/blob/b476e08abf1a9b4ac9aebe73ddcb02bdb576658e/R/mod_xml_report.R#L44)).

I was trying to use the `htmltidy` package as it has a `shiny` feature but I could not get it working. ([see](https://cran.r-project.org/web/packages/htmltidy/htmltidy.pdf)).

Can you take a look at this, please?

Thanks,
Marton

**Comment by marton-balazs-kovacs** [comment]
Dear Frederik,

I had an idea that if we could find a solution to present the preview of the XML document the same way as with the other output modules (through a rendered rmd file), we could add two additional sub-modules: mod_preview and mod_download. This way we could invite these modules inside of each output module (contib_affil, human-readable, XML, and YAML). This would make our code more concise and easier to read perhaps. What do you think? @crsh

**Comment by crsh** [comment]
Hi Marton, I'm not sure I fully understand. Would you mind answering a couple of questions to make sure we are on the same page before I dive in?

1. Are you trying to provide a preview of the XML like the one I currently produce for YAML? What do you intend to use `tidyhtml` for?
2. I do render the YAML preview in an R Markdown document much the same way as it is done in human-readable and the title page. Could this be an approach?
3. It would definitely be useful if you could abstract away the specifics of the output format and rely on the same code for preview and download for all submodules. Maybe we would need to separate code-based outputs (XML, YAML) and formatted text (human-readable, title page)? Are you looking to keep everything else as is on the interface side of things?

**Comment by marton-balazs-kovacs** [comment]
Hi Frederik,

Thank you for looking into this.
1. I wanted to provide a formatted preview for the XML document as well. Right now, it just looks like a wall of text, without line breaks and indentation. I have found that `tidyhml` provides an XML preview function that is why I wanted to use that package for this task, but it is not necessary at all to use that.
2. If you could render the XML preview from an R Markdown document that would be the best, as all output modes would use the same method. So yes, that could be an approach. I could try to do that as well but I could not get a nicely formatted output with the XML unfortunately.
3. We might have to separate the code based and the formatted text-based outputs you are right.  Or we could create a `write` function that recognizes the output type and basically provides the `content` function part of a downloadhandler.
I am intended to keep everything as is on the interface for now, but if you have any suggestions please let me know.

**Comment by crsh** [comment]
Okay, great, I think I get it. Let's try to take this step by step, focus on XML preview first and discuss the issue of separate submodules in another issue? I'll try to look into the preview later today.

**Comment by marton-balazs-kovacs** [comment]
Thanks, great! I agree I will open a new issue for the submodules.

**Comment by marton-balazs-kovacs** [comment]
@crsh Could you add the syntax highlighting as well? Then we can close this issue.
