### ISSUE TITLE
Add Oxford comma to outputs

### ISSUE THREAD

**Issue by alexholcombe** [marton-balazs-kovacs/tenzing#50]
To match APA style (but not Nature Publishing Group style), use Oxford comma for output lists such as the list of names: 
Marton Kovacs, Alex Holcombe, and Balazs Aczel

This should be very *low* priority.

**Comment by marton-balazs-kovacs** [comment]
I added the oxford comma to all outputs in 052840d0853f11d3f2cc892778b81adf407bc5ec
