### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by guiomar** [marton-balazs-kovacs/tenzing#65]
Hi! Thanks for this useful tool :)
I'm having issues with special characters, e.g. đ, š, ć, ç, ô, etc. they don't show up the the converted text.
Is there something I can do to prevent this?

**Comment by jcolomb** [comment]
@marton-balazs-kovacs the yaml export does work, but indeed the text one does not. (tested with "à"). 
maybe a UTF8 encoding problem ?

**Comment by guiomar** [comment]
Thanks @jcolomb !

**Comment by marton-balazs-kovacs** [comment]
Thanks for the feedback @guiomar and for the suggestion for the possible problem @jcolomb! I will look into this soon and get back to you.

**Comment by marton-balazs-kovacs** [comment]
Thank you again for the feedback. I changed the code and now it works with special characters as well if you run the application locally. The deployed version should be updated soon as well.

Changes are made in commit b489a31

**Comment by alexholcombe** [comment]
It seems the text you get when you "Copy to clipboard" works, which is great, but the text shown in the preview does not show the special characters, nor does it show up in the file you get if you "Download file", see these screenshots:
![image](https://user-images.githubusercontent.com/886094/133918923-c8e3a58e-e534-4d36-8a7a-03095e07a2ce.png)
![image](https://user-images.githubusercontent.com/886094/133918931-37b4cb22-4629-4c17-89d7-6d32e4af8f2c.png)

**Comment by marton-balazs-kovacs** [comment]
If I run the current version in the master branch locally, both of these outputs are working fine with the special characters provided by @guiomar and by you. Did you run the current version from this repository's master branch locally? Maybe your browser cached the previous version. Try running it in a private browser window.

**Comment by alexholcombe** [comment]
You're right, my local run of the app must have been cached. Sorry! I have deployed it now to tenzing.club

**Comment by guiomar** [comment]
Thanks a lot for the quick fix!! And again for nice tool :)
