### ISSUE TITLE
Visually distinguish links from the rest of the text

### ISSUE THREAD

**Issue by crsh** [marton-balazs-kovacs/tenzing#7]
Hi @marton-balazs-kovacs, currently links in the app look just like regular text until you mouse-over on them. How do you feel about adding some visual distinction (e.g., changing the color) to make it easier for users to discover them?

**Comment by marton-balazs-kovacs** [comment]
Hi Frederik,

I will change the color of the links to the red in the title. That way they will pop out. Thanks for noticing.

**Comment by marton-balazs-kovacs** [comment]
I have changed the color to red. 742edf72190a442ca0ab43da1e59d175157d47f7
