### ISSUE TITLE
Feature request: show corresponding author in authors list

### ISSUE THREAD

**Issue by nthun** [marton-balazs-kovacs/tenzing#74]
In the author list, put an asterix next to the corresponding author(s) name. E.g.:

John Doe<sup>1</sup>, Jane Doe<sup>2</sup>*, 
<sup>1</sup> University A
<sup>2</sup> University B
*Corresponding author

**Comment by alexholcombe** [comment]
Ideally it might output like the following:

_Correspondence should be addressed to Francisco Sotres-Bayon, Ph.D., Instituto de Fisiología CelularNeurociencias, Universidad Nacional Auto´noma de Mexico, 04510 Ciudad de Me´xico, Me´xico. E-mail:
sotres@ifc.unam.mx._ 

However, we don't have columns for postal address in the Google Sheet presently, and the number of corresponding authors is usually very few, so adding the postal address can be done manually. So @marton-balazs-kovacs and I think an acceptable solution would be to have the output just say:

_Correspondence should be addressed to Francisco Sotres-Bayon; E-mail:
sotres@ifc.unam.mx._

**Comment by jcolomb** [comment]
I think this will be recreated by the publisher anyway during manuscript submission.
To add to a manuscript draft / preprint, the corresponding author might be enough.

I would not use a star, as stars are usually for equal contribution statements.


```
John Doe1*, Jane Doe2*†, Janet Doe1
1 University A, address
2 University B, address, email
*these authors contributed equally
†Corresponding author
```

**Comment by alexholcombe** [comment]
We think Marton has successfully now implemented this. But I can't see how to close this issue, maybe I don't have permission to close issues?

**Comment by marton-balazs-kovacs** [comment]
The feature was implemented.
